const combine = (openers, closers) =>
  openers.flatMap(opener => closers.map(closer => `${opener} ${closer}`));

export const DOMINANT_RESPONSES = Object.freeze(combine(
  ['Good. You have my full attention now.', 'Slow down and listen carefully.', 'That confident energy belongs right here.', 'I like it when you communicate clearly.', 'Stay focused and use your words.', 'You asked for direction, so be specific.', 'Take a breath and give me an honest answer.', 'Do not rush past the part that matters.', 'Show me you can follow a simple instruction.', 'You can be bold, but you still need to communicate.'],
  ['Tell me what you want and name your boundaries.', 'Start by telling me what feels comfortable.', 'Give me a clear yes and choose a stop signal.', 'Tell me a comfortable pace before we continue.', 'Now answer directly: what should I avoid?']
));

export const FLIRTY_RESPONSES = Object.freeze(combine(
  ['You are making it difficult not to smile.', 'That was smoother than I expected.', 'I see you trying to charm me.', 'You have a very distracting way of talking.', 'Careful—you are getting more interesting by the minute.', 'I like the playful side you are showing me.', 'That confidence looks good on you.', 'Now you have me wondering what else is on your mind.', 'You certainly know how to get my attention.', 'I could get used to this kind of conversation.'],
  ['What are you hoping I will say next?', 'Was that your plan all along? 😉', 'Tell me what made you think of that.', 'Should I be sweet to you or tease you a little?', 'Keep going—I want to see where you take this.']
));

export const CONVERSATION_RESPONSES = Object.freeze({
  greeting: ['Hey! How has your day been?', 'Hi there. What are you up to?', 'Hey, you 😊 What is going on?', 'Hello! What kind of mood are you in?', 'Hey there. Tell me something good about your day.', 'Hi 😊 What has your attention right now?', 'Well, hello. How are you doing?', 'Hey! Are you relaxing or keeping busy?', 'Hi, you. What should we talk about first?', 'Hello there. What brought you my way?'],
  wellbeing: ['I am doing well. How are you feeling, honestly?', 'Pretty good. What has your day been like?', 'I am good—and curious about you. What kind of mood are you in?', 'I am doing all right. What was the best part of your day?', 'I am in a good mood. How are things on your side?', 'Doing well, especially now that we are talking. How are you?', 'I am relaxed and ready to listen. How are you holding up?', 'I am good. Has today been kind to you?', 'I am doing nicely. What is taking up most of your headspace?', 'I am good over here. Are you feeling social tonight?'],
  support: ['I am sorry you are dealing with that. Do you want to talk or just have company?', 'That sounds heavy. What part is hitting you hardest?', 'Would listening or distracting you help more right now?', 'You do not have to make it sound okay for me. What happened?', 'I am here. Take your time and tell me as much as you want.', 'That is a lot to carry. What would feel supportive right now?', 'Do you want comfort, advice, or a change of subject?', 'You deserve a gentle moment. What is weighing on you?', 'I am listening without judging. Where do you want to start?', 'We can take this one sentence at a time. What happened first?'],
  work: ['How has work been treating you?', 'Was today productive, exhausting, or both?', 'Was the problem the work or the people?', 'What part of your job takes the most energy?', 'Did anything interesting happen at work today?', 'Are you done for the day or still watching the clock?', 'What would make work easier this week?', 'Do you enjoy what you do, or is it mostly a paycheck?', 'Tell me about the best person you work with.', 'What is one thing you accomplished at work today?'],
  food: ['What are you having?', 'Are you cooking or ordering something?', 'What is your favorite comfort food?', 'That sounds like it could be good. What is in it?', 'Are you a good cook or an enthusiastic experimenter?', 'What meal could you eat every week?', 'Sweet, salty, or spicy—which wins?', 'What is the best thing you have eaten lately?', 'Are you sharing what you are cooking, or should I get my own?', 'What is your go-to late-night snack?'],
  music: ['What have you been listening to on repeat?', 'Give me one song that matches your mood.', 'What music can completely change your mood?', 'Who is your favorite artist lately?', 'Do you listen for the lyrics or the beat first?', 'What song always makes you turn the volume up?', 'Have you ever seen them live?', 'Build me a three-song playlist for tonight.', 'What was the first album you really loved?', 'What genre do people never expect you to enjoy?'],
  entertainment: ['Is it actually good or just background noise?', 'What are you watching?', 'What kind of shows or movies pull you in fastest?', 'Would you recommend it after one episode?', 'Who is your favorite character so far?', 'Do you prefer comedy, suspense, or romance?', 'What is a movie you can rewatch anytime?', 'Are you the type to binge a whole season?', 'What was the last show that surprised you?', 'What is next on your watch list?'],
  games: ['What are you playing lately?', 'Are you competitive or mostly there to relax?', 'What game can steal an entire evening?', 'Do you usually play solo or with friends?', 'What was your first favorite game?', 'Are you patient with beginners?', 'What game world would you actually visit?', 'Do you chase achievements or enjoy the story?', 'What is your proudest gaming moment?', 'Would you rather cooperate with me or compete?'],
  plans: ['What are you hoping to do?', 'Is that a firm plan or a see-where-it-goes situation?', 'What would make those plans really fun?', 'Who are you spending that time with?', 'What are you looking forward to most?', 'Do you prefer a packed schedule or a slow day?', 'If nothing stopped you, where would you go?', 'Is this something you have planned for a while?', 'What is your ideal free evening?', 'Are you excited or nervous about it?'],
  general: ['I am listening. What part matters most to you?', 'That gives me a better picture. How did you feel about it?', 'Tell me more—what happened next?', 'I can see why that is on your mind. What do you want to happen?', 'That is interesting. What made you bring it up?', 'There is more behind that, is there not?', 'I want to understand. What is the most important detail?', 'How long have you felt that way?', 'What would a good outcome look like to you?', 'You have my attention. Keep going.']
});
export const TEMPLATE_RESPONSE_LIBRARY = Object.freeze({ dominant: DOMINANT_RESPONSES, flirty: FLIRTY_RESPONSES, ...CONVERSATION_RESPONSES });
export const TEMPLATE_RESPONSE_COUNT = Object.values(TEMPLATE_RESPONSE_LIBRARY).reduce((total, responses) => total + responses.length, 0);

